name: Syrical
main: com.syrical.dsm.Main
version: 1.0 Alpha
commands:
    givesword:
      description: Gives a sword.
      usage: /<command>
    netherportal:
      description: Teleports you to the nether in front of the portal.
      usage: /<command>
    spawn:
      description: Teleports you to spawn.
      usage: /<command>
    glow:
      description: Puts glowstone above your head.
      usage: /<command>
    jungle:
      description: Spawn a jungle log 2 blocks in the X direction.
      usage: /<command>
    jockey:
      description: Spawn spider jockey.
      usage: /<command>
    nv:
      description: Gives you nightvision.
      usage: /<command>
    color:
      description: Selects a default color.
      usage: /<command>