name: Syrical
main: com.syrical.dsm.Main
version: 1.0 Alpha
commands:
    givesword:
      description: Gives a sword.
      usage: /<command>
    netherportal:
      description: Teleports you to the nether in front of the portal.
      usage: /<command>
    spawn:
      description: Teleports you to spawn.
      usage: /<command>
    glow:
      description: Puts glowstone above your head.
      usage: /<command>
    jungle:
      description: Spawn a jungle log 2 blocks in the X direction.
      usage: /<command>
    jockey:
      description: Spawn spider jockey.
      usage: /<command>
    nv:
      description: Gives you nightvision.
      usage: /<command>
    color:
      description: Selects a default color.
      usage: /<command>
    tag:
      description: Tags a block with a color.
      usage: /<command>
    colorify:
      description: Colors tagged blocks.
      usage: /<command>
    gui:
      description: Opens GUI.
      usage: /<command>
permissions:
    dsm.*:
      description: Permission for all commands.
      children:
         dsm.build: true
         dsm.destroy: true
         dsm.givesword: true
         dsm.gui: true
    dsm.build:
      description: Permission to build blocks.
    dsm.destroy:
      description: Permission to destroy blocks.
    dsm.givesword:
      description: Permission to give sword to player.
    dsm.gui:
      description: Permission to open GUI.