name: Syrical
main: com.syrical.dsm.Main
version: 1.0 Alpha
commands:
    netherportal:
      description: Teleports you to the nether.
      usage: /<command>
    spawn:
      description: Teleports you to spawn.
      usage: /<command>
    gatecalibration:
      description: Checks multiblocks.
      usage: /<command>
    gatewarp:
      description: Warps to location.
      usage: /<command>
    carinus:
      description: TPs player to Carinus
      usage: /<command>
    menu:
      description: Open Sell Menu
      usage: /<command>
permissions:
    dsm.*:
      description: Permission for all commands.
      children:
         dsm.build: true
         dsm.destroy: true
         dsm.givesword: true
         dsm.gui: true
    dsm.build:
      description: Permission to build blocks.
    dsm.destroy:
      description: Permission to destroy blocks.
    dsm.givesword:
      description: Permission to give sword to player.
    dsm.gui:
      description: Permission to open GUI.